FROM node:latest AS builder

WORKDIR /app

COPY package*.json package-lock.json ./

RUN npm install

COPY . .

RUN npm run build

FROM node:latest

WORKDIR /app

COPY package*.json package-lock.json ./

RUN npm install --only=production

COPY --from=builder /app/.next ./.next

COPY --from=builder /app/app/data ./app/data

EXPOSE 3000

CMD ["npm", "start"]
