name: Cars_Sales_ML_Regression_Project

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    networks:
      - app-network
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: backend
    networks:
      - app-network
    
networks:
  app-network:
    driver: bridge